### PR TITLE
Added JSON.stringify, don't yell at me 👉👈

### PR DESCRIPTION
**Pull request by informathemusic**

### CODE REVIEW

**Comment by informathemusic** [comment]
I never touchd chatblocks, don't yell at me 👉👈

**Comment by daanbreur** [comment]
Uhm thanks

**Comment by daanbreur** [comment]
I'll merge this 
# Merged. LOCKED

**Comment by daanbreur** [comment]
# Merged!

**Comment by daanbreur** [comment]
Can I close it?

**Pull request merged**
