### PR TITLE
Add CSS-based quotes to channel name input

### PR DESCRIPTION
**Pull request by AlcaDesign**
Before:
image
After:
image

### CODE REVIEW

**Comment by daanbreur** [comment]
Hey Alca ! Thanks for your PR. I Will check the code if it merges correctly :D and then will ask Instafluff for a Merge

**Comment by instafluff** [comment]
Whoa, thanks, Alca! I like the look of the new quotes but it looks strange having the closing quote be on the complete other side. Do you know if it's possible to have it just wrap the username?

**Comment by AlcaDesign** [comment]
It _is_ possible. Here I'm adapting [this example](https://stackoverflow.com/a/41389961/1703756) and just adding the `.text-quotes` class from [my original CodePen example](https://codepen.io/Alca/pen/GRoyLBQ) without changes. The input is now wrapped in a container and siblings with a span. The span is invisible but as the input value is added to its contents it imparts width on the container. This pushes the right quote image down the line.



That example is to dynamically resize the appearance of the input element. So here if I fix the width it works pretty well.



However this will probably break the Bootstrap CSS which I don't have any experience with.

**Comment by daanbreur** [comment]
Thanks @AlcaDesign I will try to implement it :+1:

**Comment by daanbreur** [comment]
Ok it breaks Bootstrap xD

**Comment by instafluff** [comment]
This is awesome!!!

**Pull request merged**
